export const staticTableData = [
  {
    ID: 1,
    Domain_name: '00extreme.com',
    Extension: 'com',
    Status: 'parked',
    Adult_content: 'No',
    Keywords: '[ 00 ] [ extreme ]',
  },
  {
    ID: 2,
    Domain_name: '00hrs.com',
    Extension: 'com',
    Status: 'parked',
    Adult_content: 'No',
    Keywords: '[ 00 ] [ hrs ]',
  },
  {
    ID: 3,
    Domain_name: '00k3.com',
    Extension: 'com',
    Status: 'parked',
    Adult_content: 'No',
    Keywords: '[ 00 ] [ k ] [ 3 ]',
  },
  {
    ID: 4,
    Domain_name: '00l.net',
    Extension: 'net',
    Status: 'parked',
    Adult_content: 'No',
    Keywords: '[ 00l.net ]',
  },
  {
    ID: 5,
    Domain_name: '02text.com',
    Extension: 'com',
    Status: 'parked',
    Adult_content: 'No',
    Keywords: '[ 02 ] [ text ]',
  },
  {
    ID: 6,
    Domain_name: '0zzy.com',
    Extension: 'com',
    Status: 'parked',
    Adult_content: 'No',
    Keywords: '[ 0 ] [ zz ] [ y ]',
  },
  {
    ID: 7,
    Domain_name: '1000facial.com',
    Extension: 'com',
    Status: 'parked',
    Adult_content: 'Yes',
    Keywords: '[ 1000 ] [ facial ]',
  },
  {
    ID: 8,
    Domain_name: '1000fotosgratis.com',
    Extension: 'com',
    Status: 'parked',
    Adult_content: 'No',
    Keywords: '[ 1000 ] [ fotos ] [ gratis ]',
  },
  {
    ID: 9,
    Domain_name: '1000petstores.com',
    Extension: 'com',
    Status: 'parked',
    Adult_content: 'No',
    Keywords: '[ 1000 ] [ pet ] [ stores ]',
  },
  {
    ID: 10,
    Domain_name: '1000toys.com',
    Extension: 'com',
    Status: 'parked',
    Adult_content: 'No',
    Keywords: '[ 1000 ] [ toys ]',
  },
];
